# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{gorilla-capistrano-recipes}
  s.version = "0.1.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Benny Degezelle"]
  s.date = %q{2010-08-24}
  s.description = %q{This gem allows for a clean Capfile by setting up common capistrano stuff such as Git preferences, Radiant specifics, db dump helpers, passenger or lighty restart, ...}
  s.email = %q{benny@gorilla-webdesign.be}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "gorilla-capistrano-recipes.gemspec",
     "lib/gorilla-capistrano-recipes.rb",
     "lib/gorilla-capistrano-recipes/deepmodules.rb",
     "lib/gorilla-capistrano-recipes/deploy.rb",
     "lib/gorilla-capistrano-recipes/lighttpd.rb",
     "lib/gorilla-capistrano-recipes/mysql.rb",
     "lib/gorilla-capistrano-recipes/passenger.rb",
     "lib/gorilla-capistrano-recipes/radiant.rb",
     "lib/tasks/db.rake",
     "test/helper.rb",
     "test/test_gorilla-capistrano-recipes.rb"
  ]
  s.homepage = %q{http://github.com/jomz/gorilla-capistrano-recipes}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Common capistrano recipes for Gorilla sites}
  s.test_files = [
    "test/helper.rb",
     "test/test_gorilla-capistrano-recipes.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
  end
end

